// Curso JS Moderno/55-Cotizador Prestamos Vue/src/App.vue
<!-- @format -->

<script setup>
import { ref, computed, watch } from "vue";
import Header from "./components/Header.vue";
import Button from "./components/Button.vue";
import { calcular } from "./helpers";

const cantidad = ref(10000);
const meses = ref(6);
const total = ref(0);
const min = 0;
const max = 20000;
const step = 100;

const formatear = (valor) => {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  });

  return formatter.format(valor);
};

watch([cantidad, meses], () => {
  total.value = calcular(cantidad.value, meses.value);
});

const pagoMensual = computed(() => {
  return total.value / meses.value;
});

const handleChangeDecremento = () => {
  if (cantidad.value <= min) {
    alert("Cantidad no valida");
  } else {
    cantidad.value -= step;
  }
};
const handleChangeIncremento = () => {
  if (cantidad.value >= max) {
    alert("Cantidad no valida");
  } else {
    cantidad.value += step;
  }
};
</script>

<template>
  <div class="my-20 max-w-lg mx-auto bg-white shadow p-10">
    <Header />
    <div class="flex justify-between mt-10">
      <Button :operador="'-'" :fn="handleChangeDecremento" />
      <Button :operador="'+'" :fn="handleChangeIncremento" />
    </div>
    <div class="my-5">
      <input
        class="w-full bg-gray-200 accent-lime-500 hover:accent-lime-600"
        type="range"
        :min="min"
        :max="max"
        :step="step"
        v-model.number="cantidad"
      />
      <p class="text-center my-10 text-5xl font-extrabold text-indigo-600">
        {{ formatear(cantidad) }}
      </p>

      <h2 class="text-2xl font-extrabold text-gray-500 text-center">
        Elige un <span class="text-indigo-600">Plazo </span>a pagar
      </h2>
      <select
        class="w-full p-2 bg-white border-gray-300 rounded-lg text-center text-xl font-bold text-gray-500 mt-5"
        :value="meses"
        v-model.number="meses"
      >
        <option value="6">6 Meses</option>
        <option value="12">12 Meses</option>
        <option value="24">24 Meses</option>
      </select>
    </div>
    <div v-if="total > 0" class="my-5 space-y-3 bg-gray-50 p-5">
      <h2 class="text-2xl font-extrabold text-gray-500 text-center">
        Resumen <span class="text-indigo-600">de pagos</span>
      </h2>
      <p class="text-xl text-gray-500 text-center font-bold">
        {{ meses }} Meses
      </p>
      <p class="text-xl text-gray-500 text-center font-bold">
        Total a pagar: {{ formatear(total) }}
      </p>
      <p class="text-xl text-gray-500 text-center font-bold">
        Mensuales: {{ formatear(pagoMensual) }}
      </p>
    </div>
    <p v-else class="text-2xl font-extrabold text-gray-500 text-center">
      Añade una cantidad y plazo a pagar
    </p>
  </div>
</template>

// Curso JS Moderno/54-Cotizador Prestamos/src/App.jsx
/** @format */
import { useEffect, useState } from "react";
import Header from "./components/Header";
import Button from "./components/Button";
import { formatearDinero, calcular, pagoAMeses } from "./helpers";

function App() {
  const [cantidad, setCantidad] = useState(10000);
  const [meses, setMeses] = useState(6);
  const [total, setTotal] = useState(0);
  const [pago, setPago] = useState(0);

  useEffect(() => {
    setTotal(calcular(cantidad, meses));
  }, [cantidad, meses]);

  useEffect(() => {
    setPago(pagoAMeses(total, meses));
  }, [total]);

  const min = 0;
  const max = 20000;
  const step = 100;

  const handle = (e) => {
    setCantidad(+e.target.value);
  };
  const handleClickDecremento = () => {
    if (cantidad <= min) {
      alert("Cantidad no válida");
    } else {
      setCantidad(cantidad - step);
    }
  };
  const handleClickAumento = () => {
    if (cantidad >= max) {
      alert("Cantidad no válida");
    } else {
      setCantidad(cantidad + step);
    }
  };

  return (
    <div className="my-20 max-w-lg mx-auto bg-white shadow p-10">
      <Header />
      <div className="flex justify-between my-6">
        <Button operador="-" fn={handleClickDecremento} />
        <Button operador="+" fn={handleClickAumento} />
      </div>
      <input
        type="range"
        className="w-full h-6 bg-gray-200 accent-lime-500 hover:accent-lime-600"
        onChange={handle}
        min={min}
        max={max}
        step={step}
        value={cantidad}
      />
      <p className="text-center my-10 text-5xl font-extrabold text-indigo-600">
        {formatearDinero(cantidad)}
      </p>

      <h2 className="text-2xl font-extrabold text-gray-500 text-center">
        Elige un <span className="text-indigo-500"> Plazo</span> a pagar
      </h2>
      <select
        className="mt-5 w-full p-2 bg-white border border-gray-300 rounded-lg text-center text-xl font-bold text-gray-500"
        value={meses}
        onChange={(e) => setMeses(+e.target.value)}
      >
        <option value={6}>6 Meses</option>
        <option value={12}>12 Meses</option>
        <option value={24}>24 Meses</option>
      </select>

      <div className="my-5 space-y-3 bg-gray-50 p-5">
        <h2 className="text-2xl font-extrabold text-gray-500 text-center">
          Resumen <span className="text-indigo-500"> de pagos</span>
        </h2>
        <p className="text-xl text-gray-500 text-center font-bold">
          {meses} Meses
        </p>
        <p className="text-xl text-gray-500 text-center font-bold">
          {formatearDinero(total)} Total a pagar
        </p>
        <p className="text-xl text-gray-500 text-center font-bold">
          {formatearDinero(pago)} Mensuales
        </p>
      </div>
    </div>
  );
}

export default App;
