// Curso JS Moderno/54-Cotizador Prestamos/src/components/Button.jsx
/** @format */

import React from "react";

const Button = ({ operador, fn }) => {
  return (
    <button
      type="button"
      className="h-10 w-10 flex items-center justify-center font-bold text-white text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500"
      onClick={fn}
    >
      {operador}
    </button>
  );
};

export default Button;

// Curso JS Moderno/55-Cotizador Prestamos Vue/src/components/Button.vue
<!-- @format -->

<script setup>
const props = defineProps({
  operador: String,
  fn: Function,
});
</script>
<template>
  <button
    type="button"
    class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
    @click="fn"
  >
    {{ operador }}
  </button>
</template>
